export const DiscussionActionTypes = {
  FETCH_DISCUSSIONS_START: 'FETCH_DISCUSSIONS_START',
  FETCH_DISCUSSIONS_SUCCESS: 'FETCH_DISCUSSIONS_SUCCESS',
  FETCH_DISCUSSIONS_FAILURE: 'FETCH_DISCUSSIONS_FAILURE',
  GET_DISCUSSION_START: 'GET_DISCUSSION_START',
  GET_DISCUSSION_SUCCESS: 'GET_DISCSUSSION_SUCCESS',
  GET_DISCUSSION_FAILURE: 'GET_DISCUSSION_FAILURE',
  CREATE_DISCUSSION_START: 'CREATE_DISCUSSION_START',
  CREATE_DISCUSSION_SUCCESS: 'CREATE_DISCUSSION_SUCCESS',
  CREATE_DISCUSSION_FAILURE: 'CREATE_DISCUSSION_FAILURE',
  VOTE_START: 'VOTE_START',
  VOTE_FAILURE: 'VOTE_FAILURE',
  VOTE_SUCCESS: 'VOTE_SUCCESS',
  CLEAN_ERROR_DISCUSSION: 'CLEAN_ERROR_DISCUSSION'
};
