export const DiscussionActionTypes = {
  FETCH_DISCUSSIONS_START: 'FETCH_DISCUSSIONS_START',
  FETCH_DISCUSSIONS_SUCCESS: 'FETCH_DISCUSSIONS_SUCCESS',
  FETCH_DISCUSSIONS_FAILURE: 'FETCH_DISCUSSIONS_FAILURE',
  CREATE_DISCUSSION_START: 'CREATE_DISCUSSION_START',
  CREATE_DISCUSSION_SUCCESS: 'CREATE_DISCUSSION_SUCCESS',
  CREATE_DISCUSSION_FAILURE: 'CREATE_DISCUSSION_FAILURE'
};
